# Generated by Django 4.2 on 2023-04-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkincareProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dietcategory',
            options={'verbose_name': 'Diet Category', 'verbose_name_plural': 'Diet Categories'},
        ),
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'Meals', 'verbose_name_plural': 'Meals'},
        ),
        migrations.RenameField(
            model_name='skincareproduct',
            old_name='photo_link',
            new_name='image_link',
        ),
        migrations.RemoveField(
            model_name='skincareproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='meals',
            name='ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
