# Generated by Django 4.2 on 2023-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skincareproducttype_alter_dietcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='instructions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
