# Generated by Django 4.2 on 2023-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meals_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportvideo',
            name='image',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
