# Generated by Django 4.2 on 2023-04-26 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sportvideo_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkincareProductType',
            new_name='ProductType',
        ),
    ]
