# Generated by Django 4.2 on 2023-04-26 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_skincareproducttype_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincareproduct',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.producttype'),
            preserve_default=False,
        ),
    ]
