# Generated by Django 3.2 on 2023-05-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
