# Generated by Django 4.2 on 2023-05-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='username',
        ),
    ]
